version: "3"

services:
  node:
    image: node:16.14
    container_name: studiogibli
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app

